name: chess_lens
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.5

dependencies:
  chess: ^0.8.1
  flutter:
    sdk: flutter
  flutter_stockfish_plugin:
    path: ./packages/flutter_stockfish_plugin
  google_fonts: 8.2.1
  http: ^1.6.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.6
  url_launcher: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
